helmfiles:
  - apps/nfs-subdir-external-provisioner/helmfile.yaml
  - apps/metallb/helmfile.yaml
  - apps/ingress-nginx/helmfile.yaml
  - apps/cert-manager/helmfile.yaml
  - apps/netbox/helmfile.yaml

environments:
  default:
    values:
    - values.yaml
