helmfiles:
  - apps/nfs-subdir-external-provisioner/helmfile.yaml
  - apps/metallb/helmfile.yaml
  - apps/ingress-nginx/helmfile.yaml
  - apps/cert-manager/helmfile.yaml
  - apps/metrics-server/helmfile.yaml
  - apps/kubernetes-dashboard/helmfile.yaml

environments:
  default:
    values:
    - values.yaml
