global:
  imagePullPolicy: IfNotPresent
  ingressClass: nginx

nfsSubdirProvisioner:
  imageTags:
    provisioner: v4.0.2
  host:
    server: "" #--Host of your NFS Server
    path: "" #--Path of your NFS Mount
  reclaimPolicy: Retain
  isDefault: true
  replicaCount: 2

metalLb:
  imageTags:
    controller: 0.13.7-debian-11-r9
    speaker: 0.13.7-debian-11-r8

ingressNginx:
  imageTags:
    ingressNginx: v1.4.0
    admissionWebhooks: v20220916-gd32f8c343
  metalLBloadBalancerIP: 192.168.1.225 #--Host network IP to use for all ingresses. Must be in your MetalLB scope
  httpEnabled: false
  httpsEnabled: true

certManager:
  imageTags:
    certManager: v1.10.0
    webhook: v1.10.0
    cainjector: v1.10.0
    startupapicheck: v1.10.0

netbox:
  imageTags:
    netbox: v3.2.8
    postres: 14.5.0-debian-11-r31
  app:
    loginRequired: true
    adminUsername: netboxadmin
    adminEmail: "" #--someone@somewhere.com
    hostname: "" #--Host address for netbox I.E. netbox.tinfoilcipher.co.uk
  db:
    hostname: netbox-postgresql.netbox.svc.cluster.local
    dbName: netbox
    adminUsername: netbox
    tcpPort: 5432