---
- name: Kubernetes - Ensure Packages
  include: ensure-apt.yaml

- name: Kubernetes - Ensure Service Account
  include: ensure-service-account.yaml

- name: Kubernetes - Ensure Swap Disabled
  include: ensure-swapoff.yaml

- name: Kubernetes - Control Plane Files
  include: ensure-k8s-control-files.yaml

- name: Kubernetes - Ensure Control Plane HA
  include: ensure-k8s-control-ha.yaml
...