repositories:
  - name: ingress-nginx
    url: 	https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.3.0
    atomic: true
    timeout: 300
    labels:
      app: ingress-nginx
      tier: infra
    values:
      - values_ingress_nginx.yaml.gotmpl

environments:
  default:
    values:
    - ../../values.yaml