---
- name: Kubernetes Service Account - Ensure Group
  group:
    name: "{{ service_account.name }}"
    state: present
    gid: '{{ service_account.gid | default(999) }}'
  tags:
  - k8s-data-sa

- name: Kubernetes Service Account - Ensure Configuration
  user:
    name: "{{ service_account.name }}"
    comment: "service_account.name }}"
    home: /opt/{{ service_account.name }}
    uid: '{{ service_account.id | default(1004) }}'
    shell: "{{ service_account.shell | default('/bin/nologin') }}"
    system: yes
    group: "{{ service_account.name }}"
  tags:
  - k8s-data-sa

- name: Kubernetes Service Account - Ensure wheel Membership
  user:
    name: "{{ service_account.name }}"
    groups: wheel
    append: yes
  tags:
  - k8s-data-sa
...